### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by BitLox** [SimpleHacks/hw_rng#2]
Hi, I just found your repo and tried it out, but it won't compile
The library does not seem to be detected as such after installing it, so I included the hw_rng.h file in the example manually.

Anything I'm missing here?
<details><summary>Click to expand</summary><P/>

```
Arduino: 1.8.12 (Mac OS X), Board: "Nordic nRF52840DK (PCA10056), 0.3.2 SoftDevice s140 6.1.1, Level 0 (Release)"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/player1/Library/Arduino15/packages -hardware /Users/player1/Synced/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/player1/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/player1/Synced/Documents/Arduino/libraries -fqbn=adafruit:nrf52:pca10056:softdevice=s140v6,debug=l0 -ide-version=10812 -build-path /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356 -warnings=none -build-cache /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_cache_819538 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.nrfjprog.path=/Users/player1/Library/Arduino15/packages/adafruit/tools/nrfjprog/9.4.0 -prefs=runtime.tools.nrfjprog-9.4.0.path=/Users/player1/Library/Arduino15/packages/adafruit/tools/nrfjprog/9.4.0 -prefs=runtime.tools.arm-none-eabi-gcc.path=/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -prefs=runtime.tools.arm-none-eabi-gcc-7-2017q4.path=/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -verbose /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/player1/Library/Arduino15/packages -hardware /Users/player1/Synced/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/player1/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/player1/Synced/Documents/Arduino/libraries -fqbn=adafruit:nrf52:pca10056:softdevice=s140v6,debug=l0 -ide-version=10812 -build-path /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356 -warnings=none -build-cache /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_cache_819538 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.nrfjprog.path=/Users/player1/Library/Arduino15/packages/adafruit/tools/nrfjprog/9.4.0 -prefs=runtime.tools.nrfjprog-9.4.0.path=/Users/player1/Library/Arduino15/packages/adafruit/tools/nrfjprog/9.4.0 -prefs=runtime.tools.arm-none-eabi-gcc.path=/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -prefs=runtime.tools.arm-none-eabi-gcc-7-2017q4.path=/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -verbose /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino
Using board 'pca10056' from platform in folder: /Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1
Using core 'nRF5' from platform in folder: /Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1
Detecting libraries used...
/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb -c -g -w -mfloat-abi=hard -mfpu=fpv4-sp-d16 -u _printf_float -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=64000000 -DARDUINO=10812 -DARDUINO_NRF52840_PCA10056 -DARDUINO_ARCH_NRF52 "-DARDUINO_BSP_VERSION=\"0.20.1\"" -DNRF52840_XXAA -DUSBCON -DUSE_TINYUSB -DUSB_VID=0x239A -DUSB_PID=0x8029 "-DUSB_MANUFACTURER=\"Nordic\"" "-DUSB_PRODUCT=\"nRF52840 DK\"" -DSOFTDEVICE_PRESENT -DARDUINO_NRF52_ADAFRUIT -DNRF52_SERIES -DLFS_NAME_MAX=64 -Ofast -DCFG_DEBUG=0 -DCFG_LOGGER=1 -DCFG_SYSVIEW=0 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/cmsis/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/hal -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/mdk -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/soc -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/drivers/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/drivers/src -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/softdevice/s140_nrf52_6.1.1_API/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/Source/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/config -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/portable/GCC/nrf52 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/portable/CMSIS/nrf52 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/sysview/SEGGER -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/sysview/Config -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB/Adafruit_TinyUSB_ArduinoCore -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/variants/pca10056 /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng_test01.ino.cpp -o /dev/null
Generating function prototypes...
/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb -c -g -w -mfloat-abi=hard -mfpu=fpv4-sp-d16 -u _printf_float -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=64000000 -DARDUINO=10812 -DARDUINO_NRF52840_PCA10056 -DARDUINO_ARCH_NRF52 "-DARDUINO_BSP_VERSION=\"0.20.1\"" -DNRF52840_XXAA -DUSBCON -DUSE_TINYUSB -DUSB_VID=0x239A -DUSB_PID=0x8029 "-DUSB_MANUFACTURER=\"Nordic\"" "-DUSB_PRODUCT=\"nRF52840 DK\"" -DSOFTDEVICE_PRESENT -DARDUINO_NRF52_ADAFRUIT -DNRF52_SERIES -DLFS_NAME_MAX=64 -Ofast -DCFG_DEBUG=0 -DCFG_LOGGER=1 -DCFG_SYSVIEW=0 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/cmsis/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/hal -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/mdk -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/soc -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/drivers/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/drivers/src -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/softdevice/s140_nrf52_6.1.1_API/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/Source/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/config -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/portable/GCC/nrf52 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/portable/CMSIS/nrf52 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/sysview/SEGGER -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/sysview/Config -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB/Adafruit_TinyUSB_ArduinoCore -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/variants/pca10056 /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng_test01.ino.cpp -o /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/preproc/ctags_target_for_gcc_minus_e.cpp
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
/Users/player1/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb -c -g -w -mfloat-abi=hard -mfpu=fpv4-sp-d16 -u _printf_float -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=64000000 -DARDUINO=10812 -DARDUINO_NRF52840_PCA10056 -DARDUINO_ARCH_NRF52 "-DARDUINO_BSP_VERSION=\"0.20.1\"" -DNRF52840_XXAA -DUSBCON -DUSE_TINYUSB -DUSB_VID=0x239A -DUSB_PID=0x8029 "-DUSB_MANUFACTURER=\"Nordic\"" "-DUSB_PRODUCT=\"nRF52840 DK\"" -DSOFTDEVICE_PRESENT -DARDUINO_NRF52_ADAFRUIT -DNRF52_SERIES -DLFS_NAME_MAX=64 -Ofast -DCFG_DEBUG=0 -DCFG_LOGGER=1 -DCFG_SYSVIEW=0 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/cmsis/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/hal -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/mdk -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/soc -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/drivers/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/drivers/src -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/softdevice/s140_nrf52_6.1.1_API/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/Source/include -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/config -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/portable/GCC/nrf52 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/freertos/portable/CMSIS/nrf52 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/sysview/SEGGER -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/sysview/Config -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB/Adafruit_TinyUSB_ArduinoCore -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5 -I/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/variants/pca10056 /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng_test01.ino.cpp -o /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng_test01.ino.cpp.o
In file included from /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino:1:0:
/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng.h: In static member function 'static void SimpleHacks::HW_RNG::begin()':
hw_rng.h:75:45: error: too few arguments to function 'void nrf_rng_error_correction_enable(NRF_RNG_Type*)'
             nrf_rng_error_correction_enable();

                                             ^
In file included from /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng.h:30:0,
                 from /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino:1:
/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/hal/nrf_rng.h:256:24: note: declared here
 NRF_STATIC_INLINE void nrf_rng_error_correction_enable(NRF_RNG_Type * p_reg)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino:1:0:
hw_rng.h:76:66: error: cannot convert 'nrf_rng_short_mask_t' to 'NRF_RNG_Type*' for argument '1' to 'void nrf_rng_shorts_disable(NRF_RNG_Type*, uint32_t)'
             nrf_rng_shorts_disable(NRF_RNG_SHORT_VALRDY_STOP_MASK);

                                                                  ^
hw_rng.h:77:52: error: cannot convert 'nrf_rng_task_t' to 'NRF_RNG_Type*' for argument '1' to 'void nrf_rng_task_trigger(NRF_RNG_Type*, nrf_rng_task_t)'
             nrf_rng_task_trigger(NRF_RNG_TASK_START);

                                                    ^
In file included from /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino:1:0:
/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng.h: In static member function 'static uint8_t SimpleHacks::HW_RNG::internal_get_byte()':
hw_rng.h:141:21: error: 'nrf_rng_event_get' was not declared in this scope
             while (!nrf_rng_event_get(NRF_RNG_EVENT_VALRDY));

                     ^~~~~~~~~~~~~~~~~
/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng.h:141:21: note: suggested alternative: 'nrf_rng_event_t'
             while (!nrf_rng_event_get(NRF_RNG_EVENT_VALRDY));

                     ^~~~~~~~~~~~~~~~~
                     nrf_rng_event_t
hw_rng.h:142:50: error: too few arguments to function 'uint8_t nrf_rng_random_value_get(const NRF_RNG_Type*)'
             uint8_t v = nrf_rng_random_value_get();

                                                  ^
In file included from /var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/arduino_build_548356/sketch/hw_rng.h:30:0,
                 from /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino:1:
/Users/player1/Library/Arduino15/packages/adafruit/hardware/nrf52/0.20.1/cores/nRF5/nordic/nrfx/hal/nrf_rng.h:251:27: note: declared here
 NRF_STATIC_INLINE uint8_t nrf_rng_random_value_get(NRF_RNG_Type const * p_reg)
                           ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/player1/Synced/Documents/Arduino/Libraries/hw_rng/examples/hw_rng_test01/hw_rng_test01.ino:1:0:
hw_rng.h:143:53: error: cannot convert 'nrf_rng_event_t' to 'NRF_RNG_Type*' for argument '1' to 'void nrf_rng_event_clear(NRF_RNG_Type*, nrf_rng_event_t)'
             nrf_rng_event_clear(NRF_RNG_EVENT_VALRDY);

                                                     ^
exit status 1
too few arguments to function 'void nrf_rng_error_correction_enable(NRF_RNG_Type*)'
```
</details>

**Comment by henrygab** [comment]
Hi @BitLox,

Thanks for finding this.  I confirm with Adafruit's BSP v0.20.1 I can reproduce the problem.

I took a look and discovered the root cause...  Sometime between nrfx v1.7.2 and nrfx v2.1.0, Nordic modified multiple RNG-related APIs.  When this library was released, Adafruit was using v1.7.2, but now they are using nrfx v2.1.0.  Therefore, this library currently fails to compile with the newer nrfx headers.

1. The changes needed to make this library work again are straightforward.
2. But, preferably I can enable this to work with both nrfx v1.7.2 *and* nrfx v2.1.0 simultaneously (to avoid breaking existing users).
3. This will need at least basic testing before it's pushed as an updated library.

For my own notes, this is a summary of the changes APIs.  Each of the below functions now takes an additional first parameter `NRF_RNG_Type * p_reg`:

* [ ] `nrf_rng_int_enable()`
* [ ] `nrf_rng_int_disable()`
* [ ] `nrf_rng_int_get()` --> `nrf_rng_int_enable_check()`
* [ ] `nrf_rng_task_address_get()`
* [ ] `nrf_rng_task_trigger()`
* [ ] `nrf_rng_event_address_get()`
* [ ] `nrf_rng_event_clear()`
* [ ] `nrf_rng_event_get()` --> `nrf_rng_event_check()`
* [ ] `nrf_rng_shorts_enable()`
* [ ] `nrf_rng_shorts_disable()`
* [ ] `nrf_rng_random_value_get()`
* [ ] `nrf_rng_error_correction_enable()`
* [ ] `nrf_rng_error_correction_disable()`

Since nRF52/nRF52840 have only a single RNG peripheral each, it's likely this will "just work".

I'll whip up an update in a branch ... in case you want to try the modifications untested....

**Comment by henrygab** [comment]
OK, branch pushed with changes that compile.
See [nrfx_2.1.0](https://github.com/SimpleHacks/hw_rng/tree/nrfx_2.1.0).

I have only compiled, not tested in any way.  Let me know if this works for you.

**Comment by BitLox** [comment]
Thanks, I’ll test and report back how it works (or not)

**Comment by BitLox** [comment]
Seems to compile and function as advertised.

**Comment by henrygab** [comment]
Thanks.  Glad it works for you now!

I am going to ensure it compiles properly with nrfx 1.7.2 also, then I will push an update.

**Comment by henrygab** [comment]
@BitLox  library is now updated to  v1.1.0, which includes the necessary fix.  Thanks again for reporting this!
